/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ano-ui/components/AButton/AButton.vue')['default']
    ACell: typeof import('ano-ui/components/ACell/ACell.vue')['default']
    ACellGroup: typeof import('ano-ui/components/ACellGroup/ACellGroup.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogos: typeof import('./components/AppLogos.vue')['default']
    HiCounter: typeof import('./components/HiCounter.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    UniEasyinput: typeof import('@dcloudio/uni-ui/lib/uni-easyinput/uni-easyinput.vue')['default']
    UniIcons: typeof import('@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue')['default']
    UniSection: typeof import('@dcloudio/uni-ui/lib/uni-section/uni-section.vue')['default']
  }
}
